# Customize global config options
global:
    border_size: 4
    border_offset: -1
    border_radius: -1
    active_color: "accent"
    inactive_color: "accent"

# Customize any option on a per-application basis
window_rules:
  - match: "Class"
    name: "Windows.UI.Core.CoreWindow"
    enabled: false

  - match: "Class"
    name: "XamlExplorerHostIslandWindow"
    enabled: false

  # This is just proof of concept of the customization options
  #- match: "Class"
  #  name: "MozillaWindowClass"
  #  strategy: "Regex"
  #  border_radius: 100
  #  active_color: "#ffffff"

  - match: "Title"
    name: "Flow.Launcher"
    enabled: false

  - match: "Title"
    name: "Zebar"
    enabled: false

  - match: "Title"
    name: "keyviz"
    enabled: false