# Thickness of the border
border_size: 4

# How much to shrink/expand the borders by to better fit the window size
border_offset: -1

# Radius of the corners. Leave this at -1 to let tacky-borders handle the radius, or set it to any other number to use as the radius.
border_radius: -1

# Border color for active window. Hex values (e.g. "#ffffff") and "accent" are supported.
active_color: "accent"

# Border color for inactive window. Hex values (e.g. "#ffffff") are "accent" are supported.
inactive_color: "accent"